# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-UUID
version:      1.01
version_from: lib/Class/DBI/UUID.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Data::UUID:                    0.11
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24
